events {}
 
http {
    server {
        listen 8787 http2;
 
        location /vector-mosot/ {
            grpc_pass grpc://localhost:8686;
            grpc_set_header Host $host;
            grpc_set_header X-Real-IP $remote_addr;
            grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}